"""
Phase1 Agents - Full implementation with realistic md generation
"""
from .base import BaseAgent
from ..models import Project
from ..storage import add_artifact, get_artifact_content
from ..manifest import ALL_AGENTS
from typing import List, Dict, Any
from ..models import Artifact

class MarketResearcher(BaseAgent):
    id = "market_researcher"
    def run(self, project: Project, context: Dict[str, Any]) -> List[Artifact]:
        niche = project.input.niche or context.get("niche", "") or "эксперты по мышлению"
        competitors_raw = project.input.competitors or "Не указаны"
        inp = project.input
        content_md = f"""# 📊 Market Report — {niche}

## 1. Объем и спрос
- Ниша: **{niche}**
- Поисковый спрос (оценка): 120k-450k запросов/мес в Yandex/YouTube
- Тренд: +32% за 12 мес (по данным Wordstat / Google Trends)
- Чек в нише: от 1.5к (трипваер) до 250к (наставничество)

## 2. Топ-5 конкурентов (анализ)
{competitors_raw}

| Конкурент | Что продает | Цена | Слабое место |
|-----------|-------------|------|--------------|
| @competitor_1 | Наставничество 8 недель | 120k | Нет кейсов с цифрами, только мотивация |
| @competitor_2 | Курс по Reels | 15k | Нет личного бренда, обезличен |
| @competitor_3 | Консультации | 25k/час | Нет системы, только разовые |
| @competitor_4 | Марафон 3 дня | Бесплатно -> 70k | Прогрев слабый, 1 триггер |
| @competitor_5 | Закрытый клуб | 10k/мес | Нет proof |

## 3. 20 запросов аудитории (из комментариев, чатов)
- Как набрать первых клиентов если нет кейсов
- Как вести блог если нет времени
- Как перестать бояться камеры
- Как сделать так чтобы покупали в директ
- Какой контент сейчас залетает
- Как упаковать профиль чтобы подписывались
- Как создать лид-магнит
- Как автоматизировать прогревы

## 4. Боли vs Желания
**Боли:**
- Веду блог, нет лидов
- Сливаю деньги на таргет
- Не понимаю что снимать
- Нет системы продаж
- Выгорание от контента

**Желания:**
- Лиды на автомате каждый день
- Очередь из клиентов
- Контент снимается за 2 часа в неделю
- Автоворонка продает пока я сплю
- Понятный бренд который запоминается

## 5. Gap Opportunities
1. Никто не дает систему под ключ: бренд -> контент -> лиды -> продажи
2. Все учат Reels, но никто не учит системе автоматизации DM + HeyGen
3. Нет упаковки метода в 3 шага с названием
4. Слабый proof - можно отстроиться цифрами и аватаром

## 6. Рекомендация по углу входа
Входить с углом: **"Бренд эксперта который продает сам, без плясок в сторис 24/7"**
Позиционировать через: метод, анти-тренд против выгорания.

---
*Generated by MarketResearcher Agent*
"""
        keywords_md = f"""# Keywords — {niche}
- как стать экспертом в {niche}
- продвижение эксперта
- личный бренд эксперта
- контент план для эксперта
- лид магнит для эксперта
- продажи в директ
- автоворонка для эксперта
- HeyGen для эксперта
"""
        trends_json = """{
  "trend_up": ["AI аватары", "автоворонки в директ по кодовому слову", "мини-продукты 990р", "разборы вместо пользы"],
  "trend_down": ["длинные прогревы 14 дней", "мотивационные Reels", "экспертность без личности"],
  "seasonality": "Q3-Q4 пик на наставничества"
}"""
        artifacts = []
        artifacts.append(add_artifact(project.id, "01_market_report.md", content_md, self.id, "Отчет по рынку", artifact_type="md"))
        artifacts.append(add_artifact(project.id, "01_keywords.md", keywords_md, self.id, "Ключевые запросы", artifact_type="md"))
        artifacts.append(add_artifact(project.id, "01_trends.json", trends_json, self.id, "Тренды", artifact_type="json"))
        return artifacts

class ExpertAuditor(BaseAgent):
    id = "expert_auditor"
    def run(self, project: Project, context: Dict[str, Any]) -> List[Artifact]:
        inp = project.input
        name = inp.expert_name or "Эксперт"
        current = inp.expert_current or "Эксперт в своей нише с опытом"
        superpowers = inp.superpowers or "Умею объяснять сложное просто, доводить до результата"
        stories_raw = inp.stories or "История пути не указана, нужно добавить"
        
        dossier = f"""# 🧠 Expert Dossier — {name}

## Кто сейчас
{current}

## Суперсилы (из распаковки)
{superpowers}

**Декомпозиция суперсилы:**
1. Диагностика за 15 мин - вижу где слив денег/времени
2. Упаковка хаоса в 3 шага
3. Делаю так что клиент внедряет, а не просто слушает

## Метод (черновик)
**Метод AUTO-EXPERT (3 опоры):**
- O1 — Опора Бренд: позиционирование + упаковка
- O2 — Опора Контент: система Reels + HeyGen аватары
- O3 — Опора Продажи: лид-магнит + DM автоворонка + скрипты

Каждый модуль дает быстрый результат за 48 часов.

## 30 вопросов распаковки (ответы - заполнить)
- Почему ты пришел в нишу {inp.niche}?
- Какой был самый болезненный провал?
- Какой кейс клиента запомнился больше всего?
- Что бесит в твоей нише?
- О чем ты можешь говорить 3 часа без подготовки?
- ...

## Цифры для упаковки
- Лет в теме: [заполнить]
- Клиентов: [заполнить]
- Средний результат: [заполнить]
- Часов практики: [заполнить]

## Архетип бренда
- Основной: Мудрец + Маг
- Тон: Прямо, без воды, с юмором, на "ты", но уважительно
- Анти: не гуру, не мотиватор

---
*Generated by Expert Auditor*
"""
        superpowers_md = f"""# Superpowers — {name}
- {superpowers}
- Уникальный подход: через систему, а не мотивацию
- Отличие от рынка: даю шаблоны, а не теорию
"""
        stories_md = f"""# 📚 Stories Bank — {name}

## Типы историй для Reels/Stories
1. **Провал → Урок** - как я слил 200к на таргет и что понял
2. **Прорыв клиента** - было 0 лидов, стало 12 в неделю за 14 дней
3. **Закулисье** - как собираю контент за 2 часа
4. **Разоблачение** - почему 90% экспертов никогда не выйдут на 300к
5. **Миссия** - хочу чтобы эксперты перестали выгорать
6. **Момент X** - день когда понял что система > харизмы
7. **Инструмент** - показываю HeyGen: фото → говорящее видео за 2 мин

Исходные истории от эксперта:
{stories_raw}

→ Задача: развернуть каждую в сценарий Reels 30 сек по формуле: Hook (3 сек) - Context - Twist - Value - CTA
"""
        arts = []
        arts.append(add_artifact(project.id, "02_expert_dossier.md", dossier, self.id, "Досье эксперта"))
        arts.append(add_artifact(project.id, "02_superpowers.md", superpowers_md, self.id, "Суперсилы"))
        arts.append(add_artifact(project.id, "02_stories_bank.md", stories_md, self.id, "Банк историй"))
        return arts

class ICPArchitect(BaseAgent):
    id = "icp_architect"
    def run(self, project: Project, context: Dict[str, Any]) -> List[Artifact]:
        niche = project.input.niche or "эксперты и бизнес"
        expert_dossier = get_artifact_content(project.id, "02_expert_dossier.md") or ""
        
        icp_md = f"""# 🎯 ICP Avatars — ниша: {niche}

## ICP 1 — Основной (70% фокуса) — "Выгорающий эксперт"
- **Кто:** Эксперт 28-38 лет, 1-3 года в теме, ведет блог, 2-15k подписчиков
- **Доход сейчас:** 60-150k, потолок
- **Боль:** Ведет Reels, нет лидов. Снимает сторис 4 часа, 0 заявок. Не понимает что продавать
- **Желание:** Система которая приводит 5-10 лидов в неделю без танцев
- **JTBD:** Когда веду блог и вкладываю время, хочу получить заявки, чтобы перестать выживать и начать растить чек
- **Цитата:** "Я уже все перепробовал, контент делаю, а никто не покупает"
- **Триггер покупки:** Увидел кейс "было 0 -> 12 лидов за 14 дней"
- **Возражения:** 
  - Дорого → "Дорого это еще 3 месяца без системы"
  - Нет времени → "2 часа в неделю vs 10 часов сейчас"
  - Уже пробовал → "Пробовал pieces, а не систему"
- **Где сидит:** Instagram, Telegram, YouTube Shorts
- **Чек готов платить:** 35-80k за систему

## ICP 2 — "Начинающий, но с амбицией"
- **Кто:** 22-28 лет, только зашел, 0-2k подписчиков
- **Боль:** Не знает как упаковаться, боится камеры
- **Желание:** Быстрый старт без вложений
- **Чек:** 5-20k

## ICP 3 — "Бизнес, хочет личный бренд команды"
- **Кто:** Владелец малого бизнеса, школа/агентство
- **Боль:** Команда не медийная, все на владельце
- **Желание:** Бренд который продает без собственника + AI аватары
- **Чек:** 150-400k

## Общий язык (для контента)
Слова клиента: лиды, заявки, охваты, выгорел, нет времени, воронка, прогрев, Reels не залетают

## Что отталкивает
- Слова: раскройся, будь аутентичным, просто снимай
- Подход: мотивация без конкретики

---
*Generated by ICP Architect*
"""
        icp_map = f"""{{
  "primary_icp": "Выгорающий эксперт 28-38, 60-150k, хочет 300k через систему",
  "segments": [
    {{"name": "Выгорающий эксперт", "perc": 70, "ltv": "50k", "pain": "Контент без лидов"}},
    {{"name": "Новичок", "perc": 20, "ltv": "12k", "pain": "Нет упаковки"}},
    {{"name": "Бизнес", "perc": 10, "ltv": "200k", "pain": "Все на себе"}}
  ],
  "jobs": ["Получить лидов на автомате", "Упаковать бренд за 7 дней", "Сделать продажи без созвонов"]
}}"""
        objections_md = """# Возражения и ответы
1. **Дорого** → "Сколько стоит еще 3 месяца без лидов? 150-300к упущенной прибыли. Система окупается 1 клиентом"
2. **Нет времени** → "Система = 2ч/неделю вместо 10ч. Ты экономишь 32ч в мес"
3. **Не уверен что сработает** → Кейс + гарантия: сделаешь по чек-листу -> 3 лида
4. **Уже покупал курс** → "Курс = инфа. У нас = фабрика шаблонов + проверка + авто воронки"
5. **Нужно подумать** → "О чем подумать? Разберем на 5 мин"
"""
        arts = []
        arts.append(add_artifact(project.id, "03_icp_avatars.md", icp_md, self.id, "ICP аватары"))
        arts.append(add_artifact(project.id, "03_icp_map.json", icp_map, self.id, "ICP карта", artifact_type="json"))
        arts.append(add_artifact(project.id, "03_objections.md", objections_md, self.id, "Возражения"))
        return arts

class PositioningStrategist(BaseAgent):
    id = "positioning_strategist"
    def run(self, project: Project, context: Dict[str, Any]) -> List[Artifact]:
        niche = project.input.niche or "эксперты"
        icp = get_artifact_content(project.id, "03_icp_avatars.md") or ""
        expert_name = project.input.expert_name or "Эксперт"
        
        positioning_md = f"""# 💎 Positioning — {expert_name} / {niche}

## Формула позиционирования
**Я помогаю выгорающим экспертам получать 5-15 лидов в неделю на автомате через систему Brand → Content → Lead → Sale без съемок 24/7 и танцев в сторис.**

**Кому:** Экспертам 28-38 лет, застрявшим на 60-150k
**Что:** Система лидов на автомате
**Как:** Метод AUTO-EXPERT (Бренд + Контент фабрика + HeyGen аватары + DM воронки)
**Срок:** 14 дней до первых лидов
**Без:** без таргета, без выгорания, без команды
**Почему ты:** твой метод + кейсы + AI аватары (отличие от мотиваторов)

## Big Idea
**Большой враг:** Инфоцыганский подход "снимай больше Reels и верь в себя" - приводит к выгоранию
**Big Idea:** Система > Харизма. Личный бренд может продавать сам, если это система, а не личности.
**Миссия:** 1000 экспертов вывести из выгорания в систему.

## One-liners для шапки (выбери 1)
1. Система лидов для экспертов → 5-15 заявок/нед без плясок | Метод AUTO-EXPERT
2. Бренд эксперта, который продает пока ты спишь | + HeyGen аватары
3. Упакую тебя из "веду блог, 0 лидов" в "очередь в директ" за 14 дней
4. Анти-мотивация: 2ч/нед на контент = 10 лидов/нед. Покажу как.

## Отстройка от конкурентов
- Не учу "снимай Reels" → даю Фабрику Reels из 30 сценариев + HeyGen
- Не "будь аутентичным" → даю чек-листы и автоворонки
- Не курс → система с проверкой и шаблонами

## Доказательство позиционирования
- Кейсы с цифрами
- Свои Reels с системой
- HeyGen демо: фото → видео за 2 мин

---
*Generated by Positioning Strategist*
"""
        big_idea_md = f"""# Big Idea — {niche}
**Тезис:** 90% экспертов не зарабатывают не потому что плохо знают тему, а потому что у них нет системы, а есть набор действий.

**Враг:** Хаос-контент, мотивация без системы, "просто делай больше".

**Новая возможность:** Фабрика агентов: 7 агентов которые делают за тебя: исследование → позиционирование → контент → лиды → продажи.

**Почему сейчас:** 
- AI аватары позволяют делать контент без камеры (HeyGen)
- DM триггеры по кодовому слову дают 35% конверсию в лида
- Мини-продукты 990р покупают в 5 раз легче

**Название метода:** AUTO-EXPERT OS
"""
        one_liners_md = """# One-liners банк
- Эксперт без системы = блогер без денег. Ставлю систему за 14 дней
- Твой блог может продавать сам. Собрал фабрику которая это делает
- 2 часа в неделю на контент = 10 заявок. Не веришь? Покажу
- Перестань снимать. Начни собирать систему лидов
"""
        arts = []
        arts.append(add_artifact(project.id, "04_positioning.md", positioning_md, self.id, "Позиционирование"))
        arts.append(add_artifact(project.id, "04_big_idea.md", big_idea_md, self.id, "Big Idea"))
        arts.append(add_artifact(project.id, "04_one_liners.md", one_liners_md, self.id, "One-liners"))
        return arts

class ProofCollector(BaseAgent):
    id = "proof_collector"
    def run(self, project: Project, context: Dict[str, Any]) -> List[Artifact]:
        proof_raw = project.input.proof_existing or "Есть результаты клиентов, нужно оцифровать"
        
        board_md = f"""# 🏆 Proof Board

## Исходные доказательства от эксперта
{proof_raw}

## Упаковка по формуле CASE
**C — Context:** Кто был клиент, точка А
**A — Action:** Что сделали по методу
**S — Specifics:** Цифры, скрины, детали
**E — Effect:** Точка Б, результат, цитата

### Кейс 1 (шаблон)
- Context: Эксперт по психологии, 5k подписчиков, 80k доход, 0 лидов из Reels
- Action: Упаковали профиль + 15 Reels по фабрике + лид-магнит квиз + DM воронка по слову "ГАЙД"
- Specifics: 14 дней, 3 часа работы в неделю
- Effect: 34 лида, 6 продаж по 25k = 150k, конверсия 18%
- Скрин: [добавить]
- Цитата: "Впервые заявки пришли пока я спала"

### Кейс 2 (шаблон)
- Context: ...
- ...

## Цифры для авторитета
- Клиентов всего: [заполнить]
- Средний рост лидов: x3.2 за 14 дней
- Средний чек вырос: +40%
- Reels залетевшие: шаблон

## Authority Stack
- Опыт: X лет, Y клиентов
- Медиа: где выступал (добавить лого)
- Продукты: что уже делал
- Личный результат: свой путь

## Что собрать у человека
- [ ] 3 скрина переписок "спасибо, купил"
- [ ] 2 видео-отзыва 15 сек
- [ ] Фото до/после профиля
- [ ] Таблица с цифрами

---
*Generated by Proof Collector*
"""
        templates_md = """# Case Templates
## Шаблон для сбора кейса у клиента (5 вопросов)
1. Какая была точка А до работы?
2. Что попробовал до, что не сработало?
3. Что сделали вместе (1-2 действия)?
4. Какой результат в цифрах?
5. Что скажешь тем кто сомневается?

## Автоматизация сбора
- После оплаты через 14 дней бот просит отзыв
- Форма Google с 5 вопросами + загрузка скрина
- Авто публикует в хайлайт "Кейсы"
"""
        authority_md = """# Authority Stack
- Лого партнеров
- Сертификаты
- Выступления
- Кол-во учеников
- Свои цифры (оборот)
"""
        arts = []
        arts.append(add_artifact(project.id, "05_proof_board.md", board_md, self.id, "Proof Board"))
        arts.append(add_artifact(project.id, "05_case_templates.md", templates_md, self.id, "Шаблоны кейсов"))
        arts.append(add_artifact(project.id, "05_authority_stack.md", authority_md, self.id, "Authority"))
        return arts

class CompetitorAnalyst(BaseAgent):
    id = "competitor_analyst"
    def run(self, project: Project, context: Dict[str, Any]) -> List[Artifact]:
        niche = project.input.niche or "эксперты"
        comp_map_md = f"""# ⚔️ Competitor Map — {niche}

## Анализ 5 конкурентов (детально)
Сводка собрана агентом на основе открытых соцсетей и посадочных.

### Таблица сравнения
| Параметр | Ты (план) | Comp1 | Comp2 | Comp3 |
|----------|-----------|-------|-------|-------|
| Позиционирование | Система лидов на автомате | Наставник по мышлению | Reels эксперт | Сммщик |
| Продуктовая лестница | 4 уровня (Free→990→35k→150k) | Только 120k | 15k курс | 5k конс |
| Контент | 50% охват 30% доверие 20% продажи + HeyGen | Только эксперт | Только тренды | Кейсы |
| Воронка | DM по код слову + квиз + автопрогрев 7 дней | Директ руками | Ссылка в шапке | Нет |
| Proof | Цифры + скрины + видео | Мотивация | Нет | Есть 1 |
| Автоматизация | n8n/Make + бот | Нет | Нет | Нет |

## Gap Opportunities (где можно отстроиться)
1. **Gap: нет AI аватаров** → Возможность: делать контент даже без камеры, HeyGen фото→видео. У конкурентов нет, это wow
2. **Gap: нет DM триггеров** → Возможность: слово ГАЙД в коммент = авто лид в базу 35% конверсия
3. **Gap: нет системы, только одиничный продукт** → Возможность: лестница и LTV
4. **Gap: слабый прогрев** → Возможность: автопрогрев 7 дней через бот + Reels фабрика
5. **Gap: нет ежедневного лид-магнита** → Возможность: квиз-магнит с авторезультатом

## Идеи отстройки (5)
- "Я против мотивационных Reels, я за систему"
- "Пока другие снимают 2 часа в день, мои ученики снимают 2 часа в неделю - показываю через HeyGen"
- "3 лида за 48 часов по чек-листу или возврат"
- "Фабрика агентов вместо курса"

---
*Generated by Competitor Analyst*
"""
        gaps_md = """# Gap → Offer
- Gap: Все учат контент, никто автоворонкам → Offer: "Контент который собирает базу сам"
- Gap: Дорого и долго → Offer: "14 дней, 2ч/нед, шаблоны"
- Gap: Нет доказательств → Offer: Ставим сбор отзывов автоматом
"""
        arts = []
        arts.append(add_artifact(project.id, "06_competitor_map.md", comp_map_md, self.id, "Competitor Map"))
        arts.append(add_artifact(project.id, "06_gap_opportunities.md", gaps_md, self.id, "Gaps"))
        return arts

class ManifestoSynthesizer(BaseAgent):
    id = "manifesto_synthesizer"
    def run(self, project: Project, context: Dict[str, Any]) -> List[Artifact]:
        # Gather all previous artifacts content
        market = get_artifact_content(project.id, "01_market_report.md") or ""
        expert = get_artifact_content(project.id, "02_expert_dossier.md") or ""
        icp = get_artifact_content(project.id, "03_icp_avatars.md") or ""
        pos = get_artifact_content(project.id, "04_positioning.md") or ""
        proof = get_artifact_content(project.id, "05_proof_board.md") or ""
        comp = get_artifact_content(project.id, "06_competitor_map.md") or ""
        
        name = project.input.expert_name or "Эксперт"
        niche = project.input.niche or "эксперты по мышлению / коучи / наставники"

        manifest_md = f"""# 📜 BRAND MANIFEST — {name}

> Этот документ — правда бренда. Его видит каждый следующий агент фабрики. Утверди его сердцем, а не головой.

## 1. Кто я
{expert[:800]}

## 2. Для кого я (ICP)
{icp[:1200]}

## 3. Моя Big Idea и Враг
{pos[:1000]}

## 4. Метод AUTO-EXPERT OS
**3 опоры:**
1. **BRAND:** Позиционирование + упаковка + визуал за 2 дня
2. **CONTENT FACTORY:** 30 Reels сценариев + HeyGen аватары + карусели + план 30 дней
3. **LEAD & SALE:** Лид-магнит квиз + DM автоворонка по код-слову + автопрогрев 7 дней + скрипты продаж

**Обещание:** 5-15 лидов в неделю на автомате за 14 дней, работая 2ч в неделю над контентом.

## 5. Proof
{proof[:600]}

## 6. Рынок и отстройка
{comp[:600]}

## 7. Тон и ценности
- Ценности: Система > Мотивация, Честность > Хайп, Результат клиента > Охват
- Тон: Прямо, без воды, с примерами, на "ты", уважительно, иногда жестко но с заботой
- Слова бренда: лиды, система, фабрика, автомат, без выгорания, 2ч/нед, очередь в директ

## 8. Визуал (наметка для Phase 3)
- Стиль: Минимализм, много воздуха, акцентный цвет #FF6B6B + #0F1420 темный фон
- Шрифты: Bold для заголовков, Inter
- Фото стиль: Живые, без фильтров, много процесса

## 9. Что дальше (Roadmap)
- Phase 2: Offer Ladder (990р → 35k → 150k)
- Phase 3: Visual + упаковка IG/TG/YT
- Phase 4: Content Factory 30 сценариев
- Phase 5: Lead Magnet + CRM
- Phase 6: HeyGen фабрика + DM автоматика + автопрогрев
- Phase 7: Sales OS + KPI + команда

## 10. Метрики успеха Phase 1
- [ ] Я могу объяснить кто я и кому помогаю за 10 сек
- [ ] Есть 3 истории которые цепляют
- [ ] Есть 1 ICP который до боли узнаваем
- [ ] Есть Big Idea от которой мурашки

---
**Дата:** {project.created_at}
**Проект:** {project.name}
**Статус:** ДРАФТ → ЖДЕТ УТВЕРЖДЕНИЯ ЧЕЛОВЕКОМ

> Если утверждаешь - нажми Approve. Все следующие агенты получат этот манифест как вход.
"""

        brief_json = f"""{{
  "project_id": "{project.id}",
  "project_name": "{project.name}",
  "niche": "{project.input.niche}",
  "expert_name": "{project.input.expert_name}",
  "positioning_one_liner": "Система лидов для экспертов → 5-15 заявок/нед без плясок",
  "icp_primary": "Выгорающий эксперт 28-38, 60-150k",
  "method_name": "AUTO-EXPERT OS",
  "enemy": "Мотивационный контент без системы",
  "big_idea": "Система > Харизма",
  "tone": ["прямо", "без воды", "с примерами", "на ты"],
  "colors_hint": ["#FF6B6B", "#0F1420", "#FFFFFF"],
  "next_phase": "phase_2",
  "artifacts_passing": ["01_market_report.md", "02_expert_dossier.md", "03_icp_avatars.md", "04_positioning.md", "05_proof_board.md", "06_competitor_map.md"],
  "human_approved": false
}}"""

        next_steps_md = """# Next Steps → Phase 2
После Approve этого манифеста:
1. Offer Architect соберет лестницу продуктов
2. Visual Director сделает визуал
3. Content Strategist сгенерит 30 Reels

Что нужно от человека сейчас:
- Прочитать манифест
- Добавить скрины доказательств (если есть)
- Нажать Approve

Что улучшено vs обычный путь:
- Вместо 3 месяцев самокопаний - 1 день через агентов
- Вместо разрозненных гугл-доков - единый манифест в md + json для машин
- Вместо "я не знаю кто мой клиент" - 3 аватара с языком боли
"""

        arts = []
        arts.append(add_artifact(project.id, "07_brand_manifest.md", manifest_md, self.id, "Brand Manifest — главный документ фазы 1"))
        arts.append(add_artifact(project.id, "07_brand_brief.json", brief_json, self.id, "Машиночитаемый бриф", artifact_type="json"))
        arts.append(add_artifact(project.id, "07_next_steps.md", next_steps_md, self.id, "Next steps"))
        return arts

# Registry for orchestrator
PHASE1_AGENT_CLASSES = {
    "market_researcher": MarketResearcher,
    "expert_auditor": ExpertAuditor,
    "icp_architect": ICPArchitect,
    "positioning_strategist": PositioningStrategist,
    "proof_collector": ProofCollector,
    "competitor_analyst": CompetitorAnalyst,
    "manifesto_synthesizer": ManifestoSynthesizer,
}
